name: flutter_api_stresstest
description: Flutter API stresstest.

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  fluro: any
  path_provider: any
  simple_permissions: any
  url_launcher: any
  # video_player: any
  video_player:
    path: /Users/ened/git/ened.flutter.plugins/packages/video_player
  
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true